[package]
name = "samplesheet"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
log = { version = "0.4.20", features = ["release_max_level_trace"] }
nom = "7.1.3"
serde = { version = "1.0.193", features = ["derive"] }
thiserror = "1.0.50"

